// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251214030449_Auth")]
    partial class Auth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Identities.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Domain.Identities.Entities.UserDevice", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("access_token");

                    b.Property<string>("Browser")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("browser");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("device_name");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("device_type");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastActivityDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_activity_date");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("LastModifiedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<DateTime>("LoginDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("login_date");

                    b.Property<DateTime?>("TokenExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("token_expiry_date");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("user_id");

                    b.Property<Guid>("UserId1")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id1");

                    b.HasKey("Id")
                        .HasName("pk_user_device");

                    b.HasIndex("UserId1")
                        .HasDatabaseName("ix_user_device_user_id1");

                    b.ToTable("user_device", (string)null);
                });

            modelBuilder.Entity("Domain.Models.News.Entities.News", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("category");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("LastModifiedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<DateTime>("PublishedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("published_on_utc");

                    b.Property<string>("Qoute")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("qoute");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_news");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_news_category");

                    b.HasIndex("ImageUrl")
                        .HasDatabaseName("ix_news_image_url");

                    b.HasIndex("Qoute")
                        .HasDatabaseName("ix_news_qoute");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_news_title");

                    b.ToTable("News", (string)null);
                });

            modelBuilder.Entity("Domain.Models.News.Entities.Section", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("content");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on_utc");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("heading");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("LastModifiedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<string>("NewsId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("news_id");

                    b.HasKey("Id")
                        .HasName("pk_sections");

                    b.HasIndex("Content")
                        .HasDatabaseName("ix_sections_content");

                    b.HasIndex("Heading")
                        .HasDatabaseName("ix_sections_heading");

                    b.HasIndex("NewsId")
                        .HasDatabaseName("ix_sections_news_id");

                    b.ToTable("Sections", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Opinions.Entities.Opinions", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("id");

                    b.Property<string>("AvatarKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar_key");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on_utc");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("LastModifiedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_opinions");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_opinions_name");

                    b.HasIndex("Rating")
                        .HasDatabaseName("ix_opinions_rating");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_opinions_role");

                    b.ToTable("Opinions", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Services.Entities.Features", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("id");

                    b.Property<string>("Benifit")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("benifit");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on_utc");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("desc");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("LastModifiedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("service_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_features");

                    b.HasIndex("Benifit")
                        .HasDatabaseName("ix_features_benifit");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_features_service_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_features_title");

                    b.ToTable("Features", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Services.Entities.Gallery", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on_utc");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("LastModifiedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("service_id");

                    b.HasKey("Id")
                        .HasName("pk_gallery");

                    b.HasIndex("ImageUrl")
                        .HasDatabaseName("ix_gallery_image_url");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_gallery_service_id");

                    b.ToTable("Gallery", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Services.Entities.Services", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on_utc");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("LastModifiedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<string>("LongDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("long_desc");

                    b.Property<string>("MainImage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("main_image");

                    b.Property<string>("ShortDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("short_desc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("ShortDesc")
                        .HasDatabaseName("ix_services_short_desc");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_services_title");

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Services.Entities.Statics", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on_utc");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("LastModifiedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("number");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("service_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_statics");

                    b.HasIndex("Number")
                        .HasDatabaseName("ix_statics_number");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_statics_service_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_statics_title");

                    b.ToTable("Statics", (string)null);
                });

            modelBuilder.Entity("Domain.Identities.Entities.UserDevice", b =>
                {
                    b.HasOne("Domain.Identities.Entities.User", "User")
                        .WithMany("UserDevices")
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_device_user_user_id1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.News.Entities.Section", b =>
                {
                    b.HasOne("Domain.Models.News.Entities.News", "News")
                        .WithMany("Sections")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sections_news_news_id");

                    b.Navigation("News");
                });

            modelBuilder.Entity("Domain.Models.Services.Entities.Features", b =>
                {
                    b.HasOne("Domain.Models.Services.Entities.Services", "Services")
                        .WithMany("Features")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_features_services_service_id");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Domain.Models.Services.Entities.Gallery", b =>
                {
                    b.HasOne("Domain.Models.Services.Entities.Services", "Services")
                        .WithMany("GalleryImages")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gallery_services_service_id");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Domain.Models.Services.Entities.Statics", b =>
                {
                    b.HasOne("Domain.Models.Services.Entities.Services", "Services")
                        .WithMany("Statics")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_statics_services_service_id");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Domain.Identities.Entities.User", b =>
                {
                    b.Navigation("UserDevices");
                });

            modelBuilder.Entity("Domain.Models.News.Entities.News", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Domain.Models.Services.Entities.Services", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("GalleryImages");

                    b.Navigation("Statics");
                });
#pragma warning restore 612, 618
        }
    }
}
