// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208142347_Opinions")]
    partial class Opinions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.News.Entities.News", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("category");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("LastModifiedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<DateTime>("PublishedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("published_on_utc");

                    b.Property<string>("Qoute")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("qoute");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_news");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_news_category");

                    b.HasIndex("ImageUrl")
                        .HasDatabaseName("ix_news_image_url");

                    b.HasIndex("Qoute")
                        .HasDatabaseName("ix_news_qoute");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_news_title");

                    b.ToTable("News", (string)null);
                });

            modelBuilder.Entity("Domain.Models.News.Entities.Section", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("content");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on_utc");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("heading");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("LastModifiedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<string>("NewsId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("news_id");

                    b.HasKey("Id")
                        .HasName("pk_sections");

                    b.HasIndex("Content")
                        .HasDatabaseName("ix_sections_content");

                    b.HasIndex("Heading")
                        .HasDatabaseName("ix_sections_heading");

                    b.HasIndex("NewsId")
                        .HasDatabaseName("ix_sections_news_id");

                    b.ToTable("Sections", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Opinions.Entities.Opinions", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("id");

                    b.Property<string>("AvatarKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar_key");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on_utc");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("LastModifiedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_opinions");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_opinions_name");

                    b.HasIndex("Rating")
                        .HasDatabaseName("ix_opinions_rating");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_opinions_role");

                    b.ToTable("Opinions", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Services.Entities.Features", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("id");

                    b.Property<string>("Benifit")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("benifit");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on_utc");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("desc");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("LastModifiedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("service_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_features");

                    b.HasIndex("Benifit")
                        .HasDatabaseName("ix_features_benifit");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_features_service_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_features_title");

                    b.ToTable("Features", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Services.Entities.Gallery", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on_utc");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("LastModifiedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("service_id");

                    b.HasKey("Id")
                        .HasName("pk_gallery");

                    b.HasIndex("ImageUrl")
                        .HasDatabaseName("ix_gallery_image_url");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_gallery_service_id");

                    b.ToTable("Gallery", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Services.Entities.Services", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on_utc");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("LastModifiedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<string>("LongDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("long_desc");

                    b.Property<string>("MainImage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("main_image");

                    b.Property<string>("ShortDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("short_desc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("ShortDesc")
                        .HasDatabaseName("ix_services_short_desc");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_services_title");

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Services.Entities.Statics", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on_utc");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("LastModifiedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("number");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("service_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_statics");

                    b.HasIndex("Number")
                        .HasDatabaseName("ix_statics_number");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_statics_service_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_statics_title");

                    b.ToTable("Statics", (string)null);
                });

            modelBuilder.Entity("Domain.Models.News.Entities.Section", b =>
                {
                    b.HasOne("Domain.Models.News.Entities.News", "News")
                        .WithMany("Sections")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sections_news_news_id");

                    b.Navigation("News");
                });

            modelBuilder.Entity("Domain.Models.Services.Entities.Features", b =>
                {
                    b.HasOne("Domain.Models.Services.Entities.Services", "Services")
                        .WithMany("Features")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_features_services_service_id");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Domain.Models.Services.Entities.Gallery", b =>
                {
                    b.HasOne("Domain.Models.Services.Entities.Services", "Services")
                        .WithMany("GalleryImages")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gallery_services_service_id");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Domain.Models.Services.Entities.Statics", b =>
                {
                    b.HasOne("Domain.Models.Services.Entities.Services", "Services")
                        .WithMany("Statics")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_statics_services_service_id");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Domain.Models.News.Entities.News", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Domain.Models.Services.Entities.Services", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("GalleryImages");

                    b.Navigation("Statics");
                });
#pragma warning restore 612, 618
        }
    }
}
