// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251205191501_News")]
    partial class News
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.News.Entities.News", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("category");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("LastModifiedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<DateTime>("PublishedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("published_on_utc");

                    b.Property<string>("Qoute")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("qoute");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_news");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_news_category");

                    b.HasIndex("ImageUrl")
                        .HasDatabaseName("ix_news_image_url");

                    b.HasIndex("Qoute")
                        .HasDatabaseName("ix_news_qoute");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("ix_news_title");

                    b.ToTable("News", (string)null);
                });

            modelBuilder.Entity("Domain.Models.News.Entities.Section", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("content");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on_utc");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("heading");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("LastModifiedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<string>("NewsId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("news_id");

                    b.HasKey("Id")
                        .HasName("pk_sections");

                    b.HasIndex("Content")
                        .HasDatabaseName("ix_sections_content");

                    b.HasIndex("Heading")
                        .HasDatabaseName("ix_sections_heading");

                    b.HasIndex("NewsId")
                        .HasDatabaseName("ix_sections_news_id");

                    b.ToTable("Sections", (string)null);
                });

            modelBuilder.Entity("Domain.Models.News.Entities.Section", b =>
                {
                    b.HasOne("Domain.Models.News.Entities.News", "News")
                        .WithMany("Sections")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sections_news_news_id");

                    b.Navigation("News");
                });

            modelBuilder.Entity("Domain.Models.News.Entities.News", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
